import { Navbar } from "@/components/storefront/Navbar";
import { div } from "framer-motion/client";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function StoreLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="sticky top-0 h-16 z-20 border-b  px-4  md:px-56 my-auto flex flex-col justify-center">
        <Navbar />
      </header>
      <main>{children}</main>
    </>
  );
}
